package com.optimaize.langdetect.ngram;

/**
 * Filters those that were not generated by the old n-gram generator.
 *
 * @author Fabian Kessler
 */
public class BackwardsCompatibleNgramFilter implements NgramFilter {

    private static final BackwardsCompatibleNgramFilter INSTANCE = new BackwardsCompatibleNgramFilter();

    public static NgramFilter getInstance() {
        return INSTANCE;
    }

    private BackwardsCompatibleNgramFilter() {
    }


    @Override
    public boolean use(String ngram) {
        switch (ngram.length()) {
            case 1:
                return ngram.charAt(0) != ' ';
            case 2:
                return !ngram.equals(ngram.toUpperCase());
            case 3:
                return ngram.charAt(1) !=' ' && !ngram.equals(ngram.toUpperCase());
            default:
                throw new UnsupportedOperationException("Unsupported n-gram length: "+ngram.length());
        }
    }

}
